server:
  port: 8087

spring:
  application:
    name: cloud-consule-consume-useradmin
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
