server:
  port: 7070

spring:
  application:
    name: cloud-config-server
  # config 配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/martaintao/spring-config-center-demo.git # 因为我这个是public的仓库，所以不需要认证。
      label: master
  # rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# eureka注册中心配置
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
# 配置暴端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh' # 暴露端点
