server:
  port: 9002

spring:
  application:
    name: nacos-provide-userinfo
  cloud:
    # nacos 配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
