server:
  port: 8082

spring:
  application:
    name: cloud-eureka-provide-userinfo-service
    description: cloud-eureka-provide-userinfo8081
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/springcloud2020?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
    username: root
    password: Chinaunicom@2019
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
