server:
  port: 8081

spring:
  application:
    name: cloud-provide-userinfo8081
    description: cloud-provide-userinfo8081
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/springcloud2020?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&verifyServerCertificate=false
    username: root
    password: Chinaunicom@2019
    driver-class-name: com.mysql.cj.jdbc.Driver